global_costmap:
  global_frame: map

  update_frequency: 10.0
  publish_frequency: 10.0

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - 
      name: inflation_layer
      type: 'costmap_2d::InflationLayer'
