local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0

  rolling_window: true
  width: 2
  height: 2
  resolution: 0.05

  plugins:
    - 
      name: obstacle_layer
      type: 'costmap_2d::ObstacleLayer'
    - 
      name: inflation_layer
      type: 'costmap_2d::InflationLayer'
