ws1_term:
	terminator -g terminator.conf -l ws1

ws3_path_finding:
	terminator -g terminator.conf -l ws3_path_finding

ws3_dwa:
	terminator -g terminator.conf -l ws3_dwa

ws4_term:
	terminator -g terminator.conf -l ws4